export const actionTypes = {
  SET_PRODUCTS: "SETP_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  ADDTOCART: "ADDTOCART",
  UPDATE_CART: "UPDATE_CART",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
};
